apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-service-pvc
spec:
  storageClassName: efs-sc       # aws-efs-csi-driver StorageClass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
