apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-service-pvc
spec:
  storageClassName: azurefile-csi   # Azure Files CSI driver (ReadWriteMany)
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
